### ISSUE TITLE
Enable Wiki

### ISSUE THREAD

**Issue by tajmone** [idle-PB/SQUINT#3]
Could you please enable the project's Wiki, for public editing?

It could be a useful tool to add articles on tries, comments on the PB implementation, ideas, etc., or even just links to external resources and additional readings.

**Comment by idle-PB** [comment]
haven't seen where the setting are to enable editing of the wiki.

**Comment by tajmone** [comment]
In the main page of **Settings**, under **Features**

**Comment by idle-PB** [comment]
can you test it?

**Comment by tajmone** [comment]
I confirm: the Wiki if freely editable by any GitHub user (via the WebUI)

You (and other collaborators to the repository) can clone, edit and push to the Wiki via Git, like any other repository. Non-collaborators can edit the Wiki pages only via the WebUI.

**Comment by idle-PB** [comment]
I'd prefer that only contributors had access to edit rather than anyone but can always revert if there's any issue having it open.

**Comment by tajmone** [comment]
Personally, I've never experienced any Wiki misuses in many years that I use GitHub. 

The worst that can happen is accidental deletions, etc., but since the Wiki is a repository, you can always rollback changes, drop commits, etc. So, chances that you could loose contents due to non-collaborators actions are zero.

**Comment by tajmone** [comment]
And, yes, you can freely toggle the setting that allows anyone to edit the Wiki.

In the Settings panel, there's also an "emergency" button to block all third party actions when things get nasty (e.g. people fighting and becoming abusive in Issues discussion, etc.). That button allows to momentary disable all interactions until things cool down (or when you've managed to change the repository settings to better handle some users and privileges).

**Comment by idle-PB** [comment]
ok will leave it as is and add some content.
